### ISSUE TITLE
تاثیرات استفاده از این سرتیفیکیت

### ISSUE THREAD

**Issue by MetaiR** [MohamadKh75/iOS_Development_Certificates#1]
با سلام ابتدا تشکر میکنم بابات زحمتتون
وقتی از این سرتیفیکیت استفاده کنیم ایا تاثیر خاصی در اپ ما داره؟ ایا به معنی داشتن دسترسی شما به اپ ما خواهد بود؟
یا بعدا برای دیکامپایل کردنش میشه ازش استفاده کرد؟
دقیقا چه تاثیری بر اپ ما خواهد داشت استفاده از این سرتیفیکیت

**Comment by MohamadKh75** [comment]
سلام
بنده هیچگونه دسترسی به برنامه شما نخواهم داشت
این فایل ها صرفا جهت خروجی گرفتنه

**Comment by MetaiR** [comment]
خیلی ممنون بابت زحماتتون
واقعا کمک بزرگی هست
