### ISSUE TITLE
get .ipa without apple developer account

### ISSUE THREAD

**Issue by MohammadeMBi** [MohamadKh75/iOS_Development_Certificates#10]
salam,
rahi hast ke bedone account betonim khoroji .ipa begirim?
chon in certificate ha 2rooz dige expire mishan.
mamnoon

**Comment by MohamadKh75** [comment]
<div dir="rtl">
سلام
وقت به خیر

متاسفانه هنوز کسی برای کمک پیدا نشده :(
</div>

closed due to https://github.com/MohamadKh75/iOS_Development_Certificates/issues/8

**Comment by ghelich** [comment]
> salam,
> rahi hast ke bedone account betonim khoroji .ipa begirim?
> chon in certificate ha 2rooz dige expire mishan.
> mamnoon

https://medium.com/m%CE%BBgn%CE%BEt%CE%BBr/how-to-export-a-ipa-file-from-xcode-without-a-dev-account-bac8b2645ad3

**Comment by h-assefi** [comment]
> > salam,
> > rahi hast ke bedone account betonim khoroji .ipa begirim?
> > chon in certificate ha 2rooz dige expire mishan.
> > mamnoon
> 
> https://medium.com/m%CE%BBgn%CE%BEt%CE%BBr/how-to-export-a-ipa-file-from-xcode-without-a-dev-account-bac8b2645ad3

آیا این راه حل واقعا جواب میده ؟
کسی تاییدش میکنه ؟
