### ISSUE TITLE
نیاز رمز 

### ISSUE THREAD

**Issue by saeed1366** [MohamadKh75/iOS_Development_Certificates#12]
با سلام زمانی که archive میزنم 
ازم پسورد میخواد

**Comment by MohamadKh75** [comment]
سلام
وقت به خیر

در هنگام درخواست پسورد، OK رو بزنین
نیازی به پسورد نیست

**Comment by pl4ten** [comment]
سلام وقت بخیر
منم هرچی میزنم پس میخواد

**Comment by mr-mamali** [comment]
+1
