### ISSUE TITLE
مشکل در سرتیفیکیت

### ISSUE THREAD

**Issue by rasooltaghipoor** [MohamadKh75/iOS_Development_Certificates#14]
سلام. من اپ رو که با این سرتیفیکیت ها بیلد کردم رو سعی کردم در گوشی با ای او اس 14.7  نصب کنم اما در اواخر کار خطا میده که ظاهرا مربوط به مشکل در سرتیفیکیت  هست. لطفا راهنمایی کنین.
من فایل خروجی رو در این سایت اپلود کردم و از طریق لینکش نصب کردم:
https://www.diawi.com/
خطایی که میده این هست:
Unable to install "myapp". This app cannot be installed because its integrity could not be verified.

**Comment by MohamadKh75** [comment]
سلام
وقت شما به خیر

تا جایی که اطلاع دارم، مشکلی در فایل‌ها نیست.
به صورت لوکال تست شد.

**Comment by rasooltaghipoor** [comment]
> 
> 
> سلام وقت شما به خیر
> 
> تا جایی که اطلاع دارم، مشکلی در فایل‌ها نیست. به صورت لوکال تست شد.

ممنون از توضحیتون. حقیقتش من اولین بار هست که می خوام خروجی ای او اس بگیرم و از کدمجیک استفاده کردم. در زمان نصب از مرورگر در دو بخش هشدار میده که شناسه دستگاه من در لیست پروویژن پروفایل نیست. تصاویرش رو گذاشتم در این مورد می تونین راهنمایی کنین؟
![photo5954195931215804032](https://user-images.githubusercontent.com/78169463/135211504-40532288-73eb-48f5-b386-d011f2367967.jpg)

![photo5954195931215804031](https://user-images.githubusercontent.com/78169463/135211534-62eec0a2-57aa-4aff-aa0b-6f52e570ac11.jpg)

**Comment by MohamadKh75** [comment]
خروجی با این روش، صرفا برای ارسال به استورهای دیگه‌اس
تا جایی که بنده می‌دونم، امکان نصب از طریق مرورگر با این روش وجود نداره

**Comment by rasooltaghipoor** [comment]
> 
> 
> خروجی با این روش، صرفا برای ارسال به استورهای دیگه‌اس تا جایی که بنده می‌دونم، امکان نصب از طریق مرورگر با این روش وجود نداره

درسته. خیلی ممنون از توضیحاتتون. پس من باید دنبال حساب دولوپر باشم.
