### ISSUE TITLE
How to change bundle id

### ISSUE THREAD

**Issue by amir14a** [MohamadKh75/iOS_Development_Certificates#17]
Hi
I can create .ipa file of my app with new certificate files
but I have to use com.iapps.exportapp as bundle id and I can't change it, how can I change it as you write in readme?

**Comment by MohamadKh75** [comment]
cc @mahadshahib

**Comment by mahadshahib** [comment]
> Hi
> 
> I can create .ipa file of my app with new certificate files
> 
> but I have to use com.iapps.exportapp as bundle id and I can't change it, how can I change it as you write in readme?

First export your ipa file as normal , change file extension to zip , extract zip file and select show package content from right click menu , then in your info.plist file you can change bundle id and buildVersion of your app the what you need to do is to compress Payload folder again and change file extension back to .ipa from .zip now you have same app with diffrent bundle id and same file size . You can alternatively use iosAppSigner app to change these parameters which is available for MacOS
