### ISSUE TITLE
Please Renew

### ISSUE THREAD

**Issue by starsoheil2007** [MohamadKh75/iOS_Development_Certificates#2]
This certificate will expire on April 17th, If possible, please renew it. 

Thanks.

**Comment by farshidsanati** [comment]
Renew

**Comment by Sepehr13** [comment]
+1

**Comment by Sepehr13** [comment]
رمز داره این نسخه جدیده ؟

**Comment by mohamadbastin** [comment]
سلام برای من مینویسه revoke شده

**Comment by farshidsanati** [comment]
> سلام برای من مینویسه revoke شده

برا منم همینه مشکل داره

**Comment by farshidsanati** [comment]
> رمز داره این نسخه جدیده ؟
نسخه جديد کجا بود  این که الان هست منقض شده

**Comment by farshidsanati** [comment]
![Screen Shot 2020-04-17 at 16 12 27](https://user-images.githubusercontent.com/10529560/79573916-99cd1d80-80d4-11ea-895d-595215bc0c74.png)



مشکلش جاست ؟

**Comment by farshidsanati** [comment]
![Screen Shot 2020-04-17 at 17 54 35](https://user-images.githubusercontent.com/10529560/79573974-b2d5ce80-80d4-11ea-85ab-4f59ce7adb90.png)

مشکلش جاست ؟

**Comment by mohamadbastin** [comment]
any updates?

**Comment by MohamadKh75** [comment]
Updated!
