### ISSUE TITLE
Unable To Install "AppName"

### ISSUE THREAD

**Issue by fatemehmarzoughi** [MohamadKh75/iOS_Development_Certificates#24]
@MohamadKh75 @mahadshahib 
Ba salam
man tonestam ba komake in certificate file ipa ro khoroji begiram, ama vaghti file ro dakhele iphone mikham nasb konam in error ro daram.

<img width="241" alt="Screenshot 2022-05-14 at 21 31 18" src="https://user-images.githubusercontent.com/48021528/168441646-9fb022c6-c5ca-4fe8-8247-0e4c5fcb024c.png">

In moshkel az certificate hast?

OS version : 15
certificate: latest version (5)

**Comment by mahadshahib** [comment]
You can not install .ipa apps on non-jailbroken devices without a valid code-signing , you should re-sign your .ipa with free(7days)or paid(1year) apple developer account and install it on your device , these certificates are for app export only .
