### ISSUE TITLE
used this bundle id in anardooni

### ISSUE THREAD

**Issue by hamidish** [MohamadKh75/iOS_Development_Certificates#27]
i  use com.iapps.export 
and when i send to anardoni got errror that this bulndle id used

**Comment by MohamadKh75** [comment]
cc @mahadshahib

**Comment by mahadshahib** [comment]
@hamidish, you have to change your bundle id before submitting it to app stores, provided bundle id is just for exporting purposes, and your apps need to have a unique bundle identifier for their own
