### ISSUE TITLE
No development certificates found error

### ISSUE THREAD

**Issue by ehsan12021** [MohamadKh75/iOS_Development_Certificates#28]
hi mohammad.
i,ve trying to get a release for ios with codemagic website
i,ve got this error in build ios step.

error

 AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
No development certificates available to code sign app for device deployment

Build failed :|
Failed to build for iOS

**Comment by MohamadKh75** [comment]
cc @mahadshahib

**Comment by mahadshahib** [comment]
@ehsan12021 i believe codemajic is supporting manual code signing and you can upload code signing certificates in Settings > Publish > iOS code signing > Manual

but you have to be sure your project master brach has the same bundle identifier as the one i provided , and you will have to then change bundle identifier of the codemagic exported ipa to your own ( this can be done automatically as well ) 
just be sure to add manual code signing profiles and be sure code magic recognizes them . feel free to ask any question further.
