### ISSUE TITLE
capability

### ISSUE THREAD

**Issue by Hdhdjdjjd** [MohamadKh75/iOS_Development_Certificates#29]
Hi , I've got these errors 

Provisioning profile "Iapps Provisioning Profile" doesn't support the Hotspot Configuration capability.
Provisioning profile "Iapps Provisioning Profile" doesn't include the com.apple.developer.networking.HotspotConfiguration entitlement.

How can i handle this?

**Comment by MohamadKh75** [comment]
cc @mahadshahib

**Comment by mahadshahib** [comment]
> Hi , I've got these errors 
> 
> 
> 
> Provisioning profile "Iapps Provisioning Profile" doesn't support the Hotspot Configuration capability.
> 
> Provisioning profile "Iapps Provisioning Profile" doesn't include the com.apple.developer.networking.HotspotConfiguration entitlement.
> 
> 
> 
> How can i handle this?
> 
> 
> 
> 

by registering your own developer account, unfortunately i can not provide you anything prior to default capabilities. good luck
