### ISSUE TITLE
No signing certificate "iOS Distribution" 

### ISSUE THREAD

**Issue by farshidsanati** [MohamadKh75/iOS_Development_Certificates#3]
No signing certificate "iOS Distribution" found
No "iOS Distribution" signing certificate matching team ID "A56QU79AZ6" with a private key was found.

با سلام
ممنون که نسخه جديد قرار دادین اما هنگام استفاده همچنین پیغامی دریافت میکنیم 

![Screen Shot 2020-04-17 at 17 54 35](https://user-images.githubusercontent.com/10529560/79574746-e107de00-80d5-11ea-80d1-c7a3c0f9eb84.png)

**Comment by MohamadKh75** [comment]
سلام
فایل های قبلی رو از keychain حذف کنید و با فایل های جدید خروجی بگیرید.

**Comment by farshidsanati** [comment]
لطف می کنید بگین چه جوری باید حذف کنم ؟
