### ISSUE TITLE
پیام خطا در گرفتن خروجی

### ISSUE THREAD

**Issue by solgi-7** [MohamadKh75/iOS_Development_Certificates#36]
سلام دوست عزیز 
بنده برای گرفتن خروجی به مرحله زدن دکمه Distribute App رسیدم که متأسفانه غیر فعال شده و اجازه نمی ده 
![Screen Shot 2023-06-21 at 3 50 32 PM](https://github.com/MohamadKh75/iOS_Development_Certificates/assets/116170412/a3ad80bc-4a0f-4251-b3cf-7773ccd738d3)

و روی دکمه Validate App میزنم خطا میدهد . مثل شکل زیر

![Screen Shot 2023-06-21 at 3 56 53 PM](https://github.com/MohamadKh75/iOS_Development_Certificates/assets/116170412/6203b7f7-1cdb-4650-8a1a-e18bb3a93961)

و این هم بقیه تنظيمات که انجام دادم بدین شکل است

![Screen Shot 2023-06-21 at 4 01 28 PM](https://github.com/MohamadKh75/iOS_Development_Certificates/assets/116170412/3d32ed69-5325-470c-8301-87144614e3f6)
لطفا اگر میتوانید به بنده کمک کنید.
با تشکر

**Comment by MohamadKh75** [comment]
@mahadshahib

**Comment by mahadshahib** [comment]
@solgi-7 the button is enabled in screenshots what do you mean its disabled?

**Comment by mahadshahib** [comment]
New valid certificates will be added soon
