### ISSUE TITLE
certificate is revoked

### ISSUE THREAD

**Issue by farshidsanati** [MohamadKh75/iOS_Development_Certificates#4]
![Screen Shot 2020-04-17 at 18 45 47](https://user-images.githubusercontent.com/10529560/79578664-c33d7780-80db-11ea-8513-3611caf76d1f.png)

**Comment by mohamadbastin** [comment]
anything?

**Comment by MohamadKh75** [comment]
Updated (https://github.com/MohamadKh75/iOS_Development_Certificates/commit/e338e24492c99921ab4f620c39146d2d33b42a06).

Happy coding and sorry for the delay!
