### ISSUE TITLE
revoked

### ISSUE THREAD

**Issue by amin7ranjbar** [MohamadKh75/iOS_Development_Certificates#42]
Signing certificate "Apple Distribution: Vladislav Kolchuk (7673SP667C)", serial number "788137214EAC5305BCA355A1600BACD4", is not valid for code signing. It may have been revoked or expired.

**Comment by mahadshahib** [comment]
> Signing certificate "Apple Distribution: Vladislav Kolchuk (7673SP667C)", serial number "788137214EAC5305BCA355A1600BACD4", is not valid for code signing. It may have been revoked or expired.

use provided application-
