### ISSUE TITLE
Certificate expiring in 9 days

### ISSUE THREAD

**Issue by MineTurtlee** [MohamadKh75/iOS_Development_Certificates#43]

**Comment by MohamadKh75** [comment]
Refer to readme plase

**Comment by MineTurtlee** [comment]
> Refer to readme please

refer to which section

**Comment by MohamadKh75** [comment]
> > Refer to readme please
> 
> refer to which section?

https://github.com/MohamadKh75/iOS_Development_Certificates?tab=readme-ov-file#new-method---export-app
