### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by mohamadbastin** [MohamadKh75/iOS_Development_Certificates#5]
![Screen Shot 1399-01-30 at 11 30 32 AM](https://user-images.githubusercontent.com/43618253/79630608-07765980-8168-11ea-9301-63da61c6e908.png)

**Comment by mojtabas74** [comment]
i have same problem

**Comment by Sepehr13** [comment]
still expired
![abc](https://user-images.githubusercontent.com/21054209/79836763-d4c99c80-83c5-11ea-8545-1b9de7b24013.JPG)

**Comment by MohamadKh75** [comment]
Updated (https://github.com/MohamadKh75/iOS_Development_Certificates/commit/e338e24492c99921ab4f620c39146d2d33b42a06).

Happy coding and sorry for the delay!
