### ISSUE TITLE
بروزرسانی فایل ها

### ISSUE THREAD

**Issue by T-Shamspour** [MohamadKh75/iOS_Development_Certificates#6]
سلام... 
ممنون بابت مطلبی که گذاشتین من طبق آموزش خواستم خروجی بگیرم ولی بنظر میرسه اعتبار اکانت تموم شده.
میخواستم خواهش کنم در صورت امکان بروزرسانیشون بکنید.
خیلی ممنون

**Comment by MohamadKh75** [comment]
سلام
خواهش می‌کنم
فکر نمی‌کنم مشکلی باشه
فایل‌های قدیمی رو پاک کردید؟

**Comment by T-Shamspour** [comment]
بله پاک کردم،حتی با استفاده از سایت codemagic و فایلهایی که شما گذاشتین هم
خروجی گرفتم.تو هیچکدوم از حالت ها اپ نصب نشد

**Comment by MohamadKh75** [comment]
دیگر دوستان مشکلی رو گزارش ندادن...
