### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mahadshahib** [MohamadKh75/iOS_Development_Certificates#8]
salam mamnoon babat ina momkne update shode ro gharar bedid ina yk mah dg valid hastn

**Comment by MohamadKh75** [comment]
Hi

Unfortunately, I couldn't find new certificates :(
If anybody has a developer account, please contact me!

**Comment by mahadshahib** [comment]
someOne Help us!

**Comment by h-assefi** [comment]
salam
dustan haunt rahehali peida nashode ?

**Comment by mahadshahib** [comment]
هنوز نه ولی در جریانه مذاکرات

**Comment by mahadshahib** [comment]
@HamidNE  Unfortunately!

**Comment by hamidish** [comment]
any update there?

**Comment by MohamadKh75** [comment]
Unfortunately no 😢

**Comment by devAlihh** [comment]
salam
dustan migam age hazinei lazeme jam shim chan nafari o in account o tahie konim .
ya moshkele dg hast ? 
in id telegrame mane dustan age mishe dar ertebat bashim ye rahi peida konim @Overrides

**Comment by hamidish** [comment]
> 
> 
> salam
> dustan migam age hazinei lazeme jam shim chan nafari o in account o tahie konim .
> ya moshkele dg hast ?
> in id telegrame mane dustan age mishe dar ertebat bashim ye rahi peida konim @ Overrides (https://t.me/Overrides)

salam man movafegh hastam .agar dostan digari ham bashand kheili behtar hast. id telegram bande ham in hast: rubicode1. lotfan shoma ham zakhire konid agar dostan digari ham bodand goroh dorost konid bebinim chi mishe.

**Comment by MohamadKh75** [comment]
Updated in https://github.com/MohamadKh75/iOS_Development_Certificates/commit/b1fbf48b6691bc065f0e684ff2a9faa837a1ce58!

Special thanks to @razipour1993 ❤️

**Comment by devAlihh** [comment]
> Updated in [b1fbf48](https://github.com/MohamadKh75/iOS_Development_Certificates/commit/b1fbf48b6691bc065f0e684ff2a9faa837a1ce58)!
> 
> Special thanks to @RaziPour1993 ❤️

salam o khaste nabashid , dametun garm 
khastam begam age donati chizi lazeme lotfan begid daste jami ye jobrane zahmat konim ❤️
az shoma do bozorgvar samimane tashakor mikonam .

**Comment by mahadshahib** [comment]
@hamidish @devAlihh salam hazine develper account hodod 200dolar hast va mnm moafeqm anjam she daste jami id tel manm ine ok boodin dar ertebat bashid mn native ios developrm @thantophobiaaa

**Comment by hamidish** [comment]
سلام توی سایت github نسخه جدید آپدیت اکانت گذاشتن
