### ISSUE TITLE
signing certificate is none

### ISSUE THREAD

**Issue by sajjadjafari76** [MohamadKh75/iOS_Development_Certificates#9]
salam 

signing ceritificate man none hast 

va inke error haye zir ro mide

status:
Provisioning profile "Wildcard_Dev" doesn't support the Associated Domains capability.
Provisioning profile "Wildcard_Dev" doesn't include the com.apple.developer.associated-domains entitlement.

**Comment by MohamadKh75** [comment]
<div dir="rtl">
سلام

وقت شما به خیر

متاسفانه بنده هنوز فایل‌های جدید رو نگرفتم.
به محض این‌که اوکی بشه، قرار میدم.

</div>

**Comment by sajjadjafari76** [comment]
ممنون و مچکر از شما
